### ISSUE TITLE
Could not find boost_python3

### ISSUE THREAD

**Issue by ckhung** [pathtrk/docker-cmake-opencv-boost#1]
Thanks for this Dockerfile. However, I have the following problem.

I git cloned https://github.com/mitmul/ssai-cnn and in its utils/ subdir tried to ```. build.sh``` . It gave the error message: "Could not find the following Boost libraries: boost_python3" . Doing ```find / -iname '*boost*python*'``` finds nothing. Maybe boost python need to be separately compiled and installed?

**Comment by pathtrk** [comment]
@ckhung I haven' tested, but how about forking my Dockerfile and modifying it like following,

```
RUN ./bootstrap.sh --prefix=/usr/local
```
into
```
RUN ./bootstrap.sh --prefix=/usr/local --with-python=python3.6
```

Hope it works for you.

https://github.com/pathtrk/docker-cmake-opencv-boost/blob/master/Dockerfile#L36

**Comment by ckhung** [comment]
Thanks for the hint! This worked for me:
`RUN ./bootstrap.sh --prefix=/usr/local --with-python=python3.4m`

How did I figure out?  The log showed that the failure was caused by missing 'pyconfig.h'. `find / -iname 'pyconfig.h'` shows there are these possibilities:
> /usr/local/include/python3.5m/pyconfig.h
> /usr/include/x86_64-linux-gnu/python2.7/pyconfig.h
> /usr/include/x86_64-linux-gnu/python3.4m/pyconfig.h
> /usr/include/python2.7/pyconfig.h
> /usr/include/python3.4m/pyconfig.h

`--with-python=python3.5m` did not work, but `--with-python=python3.4m` worked fine. Thanks!

Now I need to move on to deal with numpy compilation errors...
