### ISSUE TITLE
libboost*numpy.so* missing?

### ISSUE THREAD

**Issue by ckhung** [pathtrk/docker-cmake-opencv-boost#2]
After fixing [#1](https://github.com/pathtrk/docker-cmake-opencv-boost/issues/1), now I can compile boost/python programs. However, boost/numpy programs can be compiled but not linked. For example:
```
#include <boost/python/numpy.hpp>
#include <iostream>
#define BOOST_LIB_NAME "boost_numpy"
#include <boost/config/auto_link.hpp>
// see https://stackoverflow.com/a/42936160
namespace p = boost::python;
namespace np = boost::python::numpy;

int main(int argc, char **argv)
{
  Py_Initialize();
  np::initialize();
}
```

This code compiles fine:
`g++ -Wall -I /usr/include/python3.4m -c boost_numpy_test.cc`
but fails to link:
`g++ boost_numpy_test.o -lboost_python3 -lpython3.4m`
> boost_numpy_test.o: In function `main':
> boost_numpy_test.cc:(.text+0x1a): undefined reference to `boost::python::numpy::initialize(bool)'
> collect2: error: ld returned 1 exit status

Also, `find / -iname '*libboost*numpy*'` finds nothing. Is boost/numpy not compiled by default when building boost?

**Comment by pathtrk** [comment]
@ckhung Could you checkout the "numpy" branch of this repo and check how it goes? The compilation instruction goes here.

https://github.com/pathtrk/docker-cmake-opencv-boost/tree/numpy#test-run-with-this-dockerfile

Please be aware that this dockerfile use ```python:3.5.3``` as its base image, so I set up boost-python to use the version 3.5 of Python at ```/usr/local/```.

**Comment by ckhung** [comment]
It works perfectly! For a more extensive test,  [ssai-cnn](https://github.com/mitmul/ssai-cnn)  (which was written against boost<=1.62) also compiles and links perfectly after the following minor changes:
```
#include <boost/numpy.hpp>
namespace np = boost::numpy;
```
change to =>
```
#include <boost/python/numpy.hpp>
namespace np = boost::python::numpy;
```
No need to mess with CMake* at all.

Thank you so much :-)
